services:
  db:
    image: mysql:8.4
    container_name: lager_db
    environment:
      MYSQL_DATABASE: lageruthyrning_db
      MYSQL_USER: lageruser
      MYSQL_PASSWORD: lagerpass123
      MYSQL_ROOT_PASSWORD: rootpass123
    ports:
      - "3307:3306"
    volumes:
      - lager_db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: lager_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8082:80"
    depends_on:
      - db

volumes:
  lager_db_data:
